name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew app:assembleDebug
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        path: app/build/outputs/apk/debug/*.apk
    
