name: Android CI

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fetch Tags
      run: |
        git fetch --tags --force

    - name: set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: gradle

    - name: Write key
      if: ${{ ( github.event_name != 'pull_request' && github.ref == 'refs/heads/master' ) || github.ref_type == 'tag' }}
      run: |
        if [ ! -z "${{ secrets.KEY_STORE }}" ]; then
          echo >> gradle.properties
          echo mtStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties
          echo mtKeyAlias='${{ secrets.KEY_ALIAS }}' >> gradle.properties
          echo mtKeyPassword='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
          echo mtStoreFile='key.jks' >> gradle.properties
          echo ${{ secrets.KEY_STORE }} | base64 --decode > key.jks
        fi

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew app:assemble
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        path: app/build/outputs/apk/*/*.apk

    - name: Get tag annotation
      id: tag
      if: github.ref_type == 'tag'
      run: echo "message=$(git tag -l ${{ github.ref_name }} --format='%(contents)')" >> $GITHUB_OUTPUT

    - name: Create Release
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        body: ${{ steps.tag.outputs.message }}
        files: app/build/outputs/apk/release/*.apk
        prerelease: ${{ contains(github.ref_name, '-') }}